# Generated by Django 3.2.18 on 2023-02-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newroommodel',
            name='seats',
            field=models.CharField(default='0000000000|00000000000|00000000000|0000000000|00000000', max_length=1000),
        ),
    ]
