# Generated by Django 3.2.18 on 2023-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230218_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newroommodel',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
