# Generated by Django 3.2.18 on 2023-02-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_newroommodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newroommodel',
            name='number',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
