# Generated by Django 3.2.18 on 2023-02-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_newroommodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newroommodel',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
