# Generated by Django 3.2.18 on 2023-02-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_newroommodel_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('for_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.newroommodel')),
            ],
        ),
    ]
